/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Jul  5 22:08:11 2014"
#define BUILD_TIME (1404569291L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x001e0c46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x211b017dUL
#define VERSION_SANITY2 0xb8d24950UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Unix NetHack Version 3.4.3 - last build Sat Jul  5 22:08:11 2014."

